export interface Localidade {
  nome: string;
  slug: string;
  uf: 'DF' | 'GO';
  foco: string;
  whatsappMsg: string;
}

export const servicos = {
  'manutencao-eletrica': 'Manutenção Elétrica',
  'manutencao-hidraulica': 'Manutenção Hidráulica',
  'manutencao-eletronica': 'Manutenção Eletrônica'
};

export const localidades: Localidade[] = [
  { nome: 'Asa Norte', slug: 'asa-norte', uf: 'DF', foco: 'Atendimento em Asa Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Asa Norte' },
  { nome: 'Asa Sul', slug: 'asa-sul', uf: 'DF', foco: 'Atendimento em Asa Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Asa Sul' },
  { nome: 'Setor Comercial Sul', slug: 'setor-comercial-sul', uf: 'DF', foco: 'Atendimento em Setor Comercial Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Comercial Sul' },
  { nome: 'Setor Comercial Norte', slug: 'setor-comercial-norte', uf: 'DF', foco: 'Atendimento em Setor Comercial Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Comercial Norte' },
  { nome: 'Setor Bancário Sul', slug: 'setor-bancario-sul', uf: 'DF', foco: 'Atendimento em Setor Bancário Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Bancário Sul' },
  { nome: 'Setor Bancário Norte', slug: 'setor-bancario-norte', uf: 'DF', foco: 'Atendimento em Setor Bancário Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Bancário Norte' },
  { nome: 'Setor Hoteleiro Sul', slug: 'setor-hoteleiro-sul', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro Sul' },
  { nome: 'Setor Hoteleiro Norte', slug: 'setor-hoteleiro-norte', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro Norte' },
  { nome: 'Setor Hospitalar Sul', slug: 'setor-hospitalar-sul', uf: 'DF', foco: 'Atendimento em Setor Hospitalar Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hospitalar Sul' },
  { nome: 'Setor Hospitalar Norte', slug: 'setor-hospitalar-norte', uf: 'DF', foco: 'Atendimento em Setor Hospitalar Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hospitalar Norte' },
  { nome: 'Setor de Diversões Sul', slug: 'setor-de-diversoes-sul', uf: 'DF', foco: 'Atendimento em Setor de Diversões Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Diversões Sul' },
  { nome: 'Setor de Diversões Norte', slug: 'setor-de-diversoes-norte', uf: 'DF', foco: 'Atendimento em Setor de Diversões Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Diversões Norte' },
  { nome: 'Setor Militar Urbano', slug: 'setor-militar-urbano', uf: 'DF', foco: 'Atendimento em Setor Militar Urbano, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Militar Urbano' },
  { nome: 'Setor de Clubes Sul', slug: 'setor-de-clubes-sul', uf: 'DF', foco: 'Atendimento em Setor de Clubes Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Clubes Sul' },
  { nome: 'Setor de Clubes Norte', slug: 'setor-de-clubes-norte', uf: 'DF', foco: 'Atendimento em Setor de Clubes Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Clubes Norte' },
  { nome: 'Vila Planalto', slug: 'vila-planalto', uf: 'DF', foco: 'Atendimento em Vila Planalto, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Planalto' },
  { nome: 'Noroeste', slug: 'noroeste', uf: 'DF', foco: 'Atendimento em Noroeste, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Noroeste' },
  { nome: 'Cruzeiro Velho', slug: 'cruzeiro-velho', uf: 'DF', foco: 'Atendimento em Cruzeiro Velho, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Cruzeiro Velho' },
  { nome: 'Cruzeiro Novo', slug: 'cruzeiro-novo', uf: 'DF', foco: 'Atendimento em Cruzeiro Novo, Cruzeiro - DF', whatsappMsg: 'Gostaria de um orçamento para Cruzeiro Novo' },
  { nome: 'Sudoeste', slug: 'sudoeste', uf: 'DF', foco: 'Atendimento em Sudoeste, Sudoeste / Octogonal - DF', whatsappMsg: 'Gostaria de um orçamento para Sudoeste' },
  { nome: 'Octogonal', slug: 'octogonal', uf: 'DF', foco: 'Atendimento em Octogonal, Sudoeste / Octogonal - DF', whatsappMsg: 'Gostaria de um orçamento para Octogonal' },
  { nome: 'QI 01', slug: 'qi-01', uf: 'DF', foco: 'Atendimento em QI 01, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 01' },
  { nome: 'QI 05', slug: 'qi-05', uf: 'DF', foco: 'Atendimento em QI 05, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 05' },
  { nome: 'QI 07', slug: 'qi-07', uf: 'DF', foco: 'Atendimento em QI 07, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 07' },
  { nome: 'QI 09', slug: 'qi-09', uf: 'DF', foco: 'Atendimento em QI 09, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 09' },
  { nome: 'QL 02', slug: 'ql-02', uf: 'DF', foco: 'Atendimento em QL 02, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QL 02' },
  { nome: 'QL 06', slug: 'ql-06', uf: 'DF', foco: 'Atendimento em QL 06, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QL 06' },
  { nome: 'SHIS', slug: 'shis', uf: 'DF', foco: 'Atendimento em SHIS, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para SHIS' },
  { nome: 'QI 03', slug: 'qi-03', uf: 'DF', foco: 'Atendimento em QI 03, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para QI 03' },
  { nome: 'Taquari', slug: 'taquari', uf: 'DF', foco: 'Atendimento em Taquari, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para Taquari' },
  { nome: 'CA', slug: 'ca', uf: 'DF', foco: 'Atendimento em CA, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para CA' },
  { nome: 'Taguatinga Centro', slug: 'taguatinga-centro', uf: 'DF', foco: 'Atendimento em Taguatinga Centro, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Centro' },
  { nome: 'Taguatinga Norte', slug: 'taguatinga-norte', uf: 'DF', foco: 'Atendimento em Taguatinga Norte, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Norte' },
  { nome: 'Taguatinga Sul', slug: 'taguatinga-sul', uf: 'DF', foco: 'Atendimento em Taguatinga Sul, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Sul' },
  { nome: 'Setor Hoteleiro', slug: 'setor-hoteleiro', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro' },
  { nome: 'Vila Dimas', slug: 'vila-dimas', uf: 'DF', foco: 'Atendimento em Vila Dimas, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Dimas' },
  { nome: 'Setor Industrial', slug: 'setor-industrial', uf: 'DF', foco: 'Atendimento em Setor Industrial, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Industrial' },
  { nome: 'QNG', slug: 'qng', uf: 'DF', foco: 'Atendimento em QNG, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNG' },
  { nome: 'QNL', slug: 'qnl', uf: 'DF', foco: 'Atendimento em QNL, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNL' },
  { nome: 'QNM', slug: 'qnm', uf: 'DF', foco: 'Atendimento em QNM, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNM' },
  { nome: 'Ceilândia Centro', slug: 'ceilandia-centro', uf: 'DF', foco: 'Atendimento em Ceilândia Centro, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Centro' },
  { nome: 'Ceilândia Norte', slug: 'ceilandia-norte', uf: 'DF', foco: 'Atendimento em Ceilândia Norte, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Norte' },
  { nome: 'Ceilândia Sul', slug: 'ceilandia-sul', uf: 'DF', foco: 'Atendimento em Ceilândia Sul, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Sul' },
  { nome: 'P Sul', slug: 'p-sul', uf: 'DF', foco: 'Atendimento em P Sul, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para P Sul' },
  { nome: 'P Norte', slug: 'p-norte', uf: 'DF', foco: 'Atendimento em P Norte, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para P Norte' },
  { nome: 'QNN', slug: 'qnn', uf: 'DF', foco: 'Atendimento em QNN, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para QNN' },
  { nome: 'Expansão do Setor O', slug: 'expansao-do-setor-o', uf: 'DF', foco: 'Atendimento em Expansão do Setor O, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Expansão do Setor O' },
  { nome: 'Setor O', slug: 'setor-o', uf: 'DF', foco: 'Atendimento em Setor O, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Setor O' },
  { nome: 'Sol Nascente', slug: 'sol-nascente', uf: 'DF', foco: 'Atendimento em Sol Nascente, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Sol Nascente' },
  { nome: 'Pôr do Sol', slug: 'por-do-sol', uf: 'DF', foco: 'Atendimento em Pôr do Sol, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Pôr do Sol' },
  { nome: 'Samambaia Norte', slug: 'samambaia-norte', uf: 'DF', foco: 'Atendimento em Samambaia Norte, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Samambaia Norte' },
  { nome: 'Samambaia Sul', slug: 'samambaia-sul', uf: 'DF', foco: 'Atendimento em Samambaia Sul, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Samambaia Sul' },
  { nome: 'Expansão Samambaia', slug: 'expansao-samambaia', uf: 'DF', foco: 'Atendimento em Expansão Samambaia, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Expansão Samambaia' },
  { nome: 'Recanto das Emas Norte', slug: 'recanto-das-emas-norte', uf: 'DF', foco: 'Atendimento em Recanto das Emas Norte, Recanto das Emas - DF', whatsappMsg: 'Gostaria de um orçamento para Recanto das Emas Norte' },
  { nome: 'Recanto das Emas Sul', slug: 'recanto-das-emas-sul', uf: 'DF', foco: 'Atendimento em Recanto das Emas Sul, Recanto das Emas - DF', whatsappMsg: 'Gostaria de um orçamento para Recanto das Emas Sul' },
  { nome: 'Santa Maria Norte', slug: 'santa-maria-norte', uf: 'DF', foco: 'Atendimento em Santa Maria Norte, Santa Maria - DF', whatsappMsg: 'Gostaria de um orçamento para Santa Maria Norte' },
  { nome: 'Santa Maria Sul', slug: 'santa-maria-sul', uf: 'DF', foco: 'Atendimento em Santa Maria Sul, Santa Maria - DF', whatsappMsg: 'Gostaria de um orçamento para Santa Maria Sul' },
  { nome: 'Setor Central', slug: 'setor-central', uf: 'DF', foco: 'Atendimento em Setor Central, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Central' },
  { nome: 'Setor Oeste', slug: 'setor-oeste', uf: 'DF', foco: 'Atendimento em Setor Oeste, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Oeste' },
  { nome: 'Setor Sul', slug: 'setor-sul', uf: 'DF', foco: 'Atendimento em Setor Sul, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Sul' },
  { nome: 'Setor Norte', slug: 'setor-norte', uf: 'DF', foco: 'Atendimento em Setor Norte, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Norte' },
  { nome: 'Setor Leste', slug: 'setor-leste', uf: 'DF', foco: 'Atendimento em Setor Leste, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Leste' },
  { nome: 'Guará I', slug: 'guara-i', uf: 'DF', foco: 'Atendimento em Guará I, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para Guará I' },
  { nome: 'Guará II', slug: 'guara-ii', uf: 'DF', foco: 'Atendimento em Guará II, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para Guará II' },
  { nome: 'QE', slug: 'qe', uf: 'DF', foco: 'Atendimento em QE, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para QE' },
  { nome: 'QI', slug: 'qi', uf: 'DF', foco: 'Atendimento em QI, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para QI' },
  { nome: 'Metropolitana', slug: 'metropolitana', uf: 'DF', foco: 'Atendimento em Metropolitana, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Metropolitana' },
  { nome: 'Divinéia', slug: 'divineia', uf: 'DF', foco: 'Atendimento em Divinéia, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Divinéia' },
  { nome: 'Candangolândia', slug: 'candangolandia', uf: 'DF', foco: 'Atendimento em Candangolândia, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Candangolândia' },
  { nome: 'Águas Claras Sul', slug: 'aguas-claras-sul', uf: 'DF', foco: 'Atendimento em Águas Claras Sul, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Águas Claras Sul' },
  { nome: 'Águas Claras Norte', slug: 'aguas-claras-norte', uf: 'DF', foco: 'Atendimento em Águas Claras Norte, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Águas Claras Norte' },
  { nome: 'Arniqueiras', slug: 'arniqueiras', uf: 'DF', foco: 'Atendimento em Arniqueiras, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Arniqueiras' },
  { nome: 'Colônia Agrícola Samambaia', slug: 'colonia-agricola-samambaia', uf: 'DF', foco: 'Atendimento em Colônia Agrícola Samambaia, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Colônia Agrícola Samambaia' },
  { nome: 'Rua 03', slug: 'rua-03', uf: 'DF', foco: 'Atendimento em Rua 03, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 03' },
  { nome: 'Rua 08', slug: 'rua-08', uf: 'DF', foco: 'Atendimento em Rua 08, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 08' },
  { nome: 'Rua 12', slug: 'rua-12', uf: 'DF', foco: 'Atendimento em Rua 12, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 12' },
  { nome: 'Riacho Fundo I', slug: 'riacho-fundo-i', uf: 'DF', foco: 'Atendimento em Riacho Fundo I, Riacho Fundo - DF', whatsappMsg: 'Gostaria de um orçamento para Riacho Fundo I' },
  { nome: 'Riacho Fundo II', slug: 'riacho-fundo-ii', uf: 'DF', foco: 'Atendimento em Riacho Fundo II, Riacho Fundo - DF', whatsappMsg: 'Gostaria de um orçamento para Riacho Fundo II' },
  { nome: 'Paranoá Centro', slug: 'paranoa-centro', uf: 'DF', foco: 'Atendimento em Paranoá Centro, Paranoá - DF', whatsappMsg: 'Gostaria de um orçamento para Paranoá Centro' },
  { nome: 'Itapoã', slug: 'itapoa', uf: 'DF', foco: 'Atendimento em Itapoã, Paranoá - DF', whatsappMsg: 'Gostaria de um orçamento para Itapoã' },
  { nome: 'Sobradinho I', slug: 'sobradinho-i', uf: 'DF', foco: 'Atendimento em Sobradinho I, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Sobradinho I' },
  { nome: 'Sobradinho II', slug: 'sobradinho-ii', uf: 'DF', foco: 'Atendimento em Sobradinho II, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Sobradinho II' },
  { nome: 'Nova Colina', slug: 'nova-colina', uf: 'DF', foco: 'Atendimento em Nova Colina, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Nova Colina' },
  { nome: 'Setor Tradicional', slug: 'setor-tradicional', uf: 'DF', foco: 'Atendimento em Setor Tradicional, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Tradicional' },
  { nome: 'Arapoanga', slug: 'arapoanga', uf: 'DF', foco: 'Atendimento em Arapoanga, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Arapoanga' },
  { nome: 'Vale do Amanhecer', slug: 'vale-do-amanhecer', uf: 'DF', foco: 'Atendimento em Vale do Amanhecer, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Vale do Amanhecer' },
  { nome: 'Jardim Botânico', slug: 'jardim-botanico', uf: 'DF', foco: 'Atendimento em Jardim Botânico, Jardim Botânico - DF', whatsappMsg: 'Gostaria de um orçamento para Jardim Botânico' },
  { nome: 'São Sebastião', slug: 'sao-sebastiao', uf: 'DF', foco: 'Atendimento em São Sebastião, Jardim Botânico - DF', whatsappMsg: 'Gostaria de um orçamento para São Sebastião' },
  { nome: 'Vila Nova', slug: 'vila-nova', uf: 'DF', foco: 'Atendimento em Vila Nova, São Sebastião - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Nova' },
  { nome: 'Morro Azul', slug: 'morro-azul', uf: 'DF', foco: 'Atendimento em Morro Azul, São Sebastião - DF', whatsappMsg: 'Gostaria de um orçamento para Morro Azul' },
  { nome: 'SMPW', slug: 'smpw', uf: 'DF', foco: 'Atendimento em SMPW, Park Way - DF', whatsappMsg: 'Gostaria de um orçamento para SMPW' },
  { nome: 'Quadras Park Way', slug: 'quadras-park-way', uf: 'DF', foco: 'Atendimento em Quadras Park Way, Park Way - DF', whatsappMsg: 'Gostaria de um orçamento para Quadras Park Way' },
  { nome: 'Setor de Indústria e Abastecimento', slug: 'setor-de-industria-e-abastecimento', uf: 'DF', foco: 'Atendimento em Setor de Indústria e Abastecimento, SIA - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Indústria e Abastecimento' },
  { nome: 'Cidade Estrutural', slug: 'cidade-estrutural', uf: 'DF', foco: 'Atendimento em Cidade Estrutural, Estrutural - DF', whatsappMsg: 'Gostaria de um orçamento para Cidade Estrutural' },
  { nome: 'Área Rural de Águas Lindas de Goiás', slug: 'area-rural-de-aguas-lindas-de-goias', uf: 'GO', foco: 'Atendimento em Área Rural de Águas Lindas de Goiás, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Área Rural de Águas Lindas de Goiás' },
  { nome: 'Camping Clube', slug: 'camping-clube', uf: 'GO', foco: 'Atendimento em Camping Clube, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Camping Clube' },
  { nome: 'Chácaras Águas Lindas', slug: 'chacaras-aguas-lindas', uf: 'GO', foco: 'Atendimento em Chácaras Águas Lindas, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras Águas Lindas' },
  { nome: 'Chácaras Cachoeira da Mata', slug: 'chacaras-cachoeira-da-mata', uf: 'GO', foco: 'Atendimento em Chácaras Cachoeira da Mata, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras Cachoeira da Mata' },
  { nome: 'Chácaras Coimbra', slug: 'chacaras-coimbra', uf: 'GO', foco: 'Atendimento em Chácaras Coimbra, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras Coimbra' },
  { nome: 'Chácaras do Entorno', slug: 'chacaras-do-entorno', uf: 'GO', foco: 'Atendimento em Chácaras do Entorno, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras do Entorno' },
  { nome: 'Chácaras Quedas do Descoberto', slug: 'chacaras-quedas-do-descoberto', uf: 'GO', foco: 'Atendimento em Chácaras Quedas do Descoberto, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras Quedas do Descoberto' },
  { nome: 'Chácaras Quedas do Descoberto II', slug: 'chacaras-quedas-do-descoberto-ii', uf: 'GO', foco: 'Atendimento em Chácaras Quedas do Descoberto II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Chácaras Quedas do Descoberto II' },
  { nome: 'Cidade do Entorno', slug: 'cidade-do-entorno', uf: 'GO', foco: 'Atendimento em Cidade do Entorno, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Cidade do Entorno' },
  { nome: 'Cidade Jardim', slug: 'cidade-jardim', uf: 'GO', foco: 'Atendimento em Cidade Jardim, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Cidade Jardim' },
  { nome: 'Condomínio Bela Vista da Barragem I', slug: 'condominio-bela-vista-da-barragem-i', uf: 'GO', foco: 'Atendimento em Condomínio Bela Vista da Barragem I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Condomínio Bela Vista da Barragem I' },
  { nome: 'Condomínio Residencial Embaixador', slug: 'condominio-residencial-embaixador', uf: 'GO', foco: 'Atendimento em Condomínio Residencial Embaixador, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Condomínio Residencial Embaixador' },
  { nome: 'Condomínio Solar da Barragem', slug: 'condominio-solar-da-barragem', uf: 'GO', foco: 'Atendimento em Condomínio Solar da Barragem, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Condomínio Solar da Barragem' },
  { nome: 'Jardim Águas Lindas II', slug: 'jardim-aguas-lindas-ii', uf: 'GO', foco: 'Atendimento em Jardim Águas Lindas II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Águas Lindas II' },
  { nome: 'Jardim Alterosa', slug: 'jardim-alterosa', uf: 'GO', foco: 'Atendimento em Jardim Alterosa, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Alterosa' },
  { nome: 'Jardim América I', slug: 'jardim-america-i', uf: 'GO', foco: 'Atendimento em Jardim América I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América I' },
  { nome: 'Jardim América II', slug: 'jardim-america-ii', uf: 'GO', foco: 'Atendimento em Jardim América II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América II' },
  { nome: 'Jardim América III', slug: 'jardim-america-iii', uf: 'GO', foco: 'Atendimento em Jardim América III, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América III' },
  { nome: 'Jardim América IV', slug: 'jardim-america-iv', uf: 'GO', foco: 'Atendimento em Jardim América IV, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América IV' },
  { nome: 'Jardim América V', slug: 'jardim-america-v', uf: 'GO', foco: 'Atendimento em Jardim América V, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América V' },
  { nome: 'Jardim América VI', slug: 'jardim-america-vi', uf: 'GO', foco: 'Atendimento em Jardim América VI, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim América VI' },
  { nome: 'Jardim Brasília', slug: 'jardim-brasilia', uf: 'GO', foco: 'Atendimento em Jardim Brasília, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Brasília' },
  { nome: 'Jardim Califórnia', slug: 'jardim-california', uf: 'GO', foco: 'Atendimento em Jardim Califórnia, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Califórnia' },
  { nome: 'Jardim da Barragem I', slug: 'jardim-da-barragem-i', uf: 'GO', foco: 'Atendimento em Jardim da Barragem I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem I' },
  { nome: 'Jardim da Barragem II', slug: 'jardim-da-barragem-ii', uf: 'GO', foco: 'Atendimento em Jardim da Barragem II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem II' },
  { nome: 'Jardim da Barragem III', slug: 'jardim-da-barragem-iii', uf: 'GO', foco: 'Atendimento em Jardim da Barragem III, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem III' },
  { nome: 'Jardim da Barragem IV', slug: 'jardim-da-barragem-iv', uf: 'GO', foco: 'Atendimento em Jardim da Barragem IV, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem IV' },
  { nome: 'Jardim da Barragem V', slug: 'jardim-da-barragem-v', uf: 'GO', foco: 'Atendimento em Jardim da Barragem V, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem V' },
  { nome: 'Jardim da Barragem VI', slug: 'jardim-da-barragem-vi', uf: 'GO', foco: 'Atendimento em Jardim da Barragem VI, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim da Barragem VI' },
  { nome: 'Jardim das Laranjeiras I', slug: 'jardim-das-laranjeiras-i', uf: 'GO', foco: 'Atendimento em Jardim das Laranjeiras I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim das Laranjeiras I' },
  { nome: 'Jardim das Oliveiras I', slug: 'jardim-das-oliveiras-i', uf: 'GO', foco: 'Atendimento em Jardim das Oliveiras I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim das Oliveiras I' },
  { nome: 'Jardim das Oliveiras II', slug: 'jardim-das-oliveiras-ii', uf: 'GO', foco: 'Atendimento em Jardim das Oliveiras II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim das Oliveiras II' },
  { nome: 'Jardim do Entorno I', slug: 'jardim-do-entorno-i', uf: 'GO', foco: 'Atendimento em Jardim do Entorno I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim do Entorno I' },
  { nome: 'Jardim dos Pinheiros', slug: 'jardim-dos-pinheiros', uf: 'GO', foco: 'Atendimento em Jardim dos Pinheiros, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim dos Pinheiros' },
  { nome: 'Jardim Guaíra I', slug: 'jardim-guaira-i', uf: 'GO', foco: 'Atendimento em Jardim Guaíra I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Guaíra I' },
  { nome: 'Jardim Guaíra II', slug: 'jardim-guaira-ii', uf: 'GO', foco: 'Atendimento em Jardim Guaíra II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Guaíra II' },
  { nome: 'Jardim Pepita', slug: 'jardim-pepita', uf: 'GO', foco: 'Atendimento em Jardim Pepita, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Pepita' },
  { nome: 'Jardim Pérola da Barragem I', slug: 'jardim-perola-da-barragem-i', uf: 'GO', foco: 'Atendimento em Jardim Pérola da Barragem I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Pérola da Barragem I' },
  { nome: 'Jardim Pérola da Barragem II', slug: 'jardim-perola-da-barragem-ii', uf: 'GO', foco: 'Atendimento em Jardim Pérola da Barragem II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Pérola da Barragem II' },
  { nome: 'Jardim Planalto', slug: 'jardim-planalto', uf: 'GO', foco: 'Atendimento em Jardim Planalto, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Planalto' },
  { nome: 'Jardim Querência', slug: 'jardim-querencia', uf: 'GO', foco: 'Atendimento em Jardim Querência, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Querência' },
  { nome: 'Jardim Recanto', slug: 'jardim-recanto', uf: 'GO', foco: 'Atendimento em Jardim Recanto, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Recanto' },
  { nome: 'Jardim Santa Lúcia', slug: 'jardim-santa-lucia', uf: 'GO', foco: 'Atendimento em Jardim Santa Lúcia, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Santa Lúcia' },
  { nome: 'Jardim Santana', slug: 'jardim-santana', uf: 'GO', foco: 'Atendimento em Jardim Santana, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Santana' },
  { nome: 'Jardim Vitória', slug: 'jardim-vitoria', uf: 'GO', foco: 'Atendimento em Jardim Vitória, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Jardim Vitória' },
  { nome: 'Laranjeiras II', slug: 'laranjeiras-ii', uf: 'GO', foco: 'Atendimento em Laranjeiras II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Laranjeiras II' },
  { nome: 'Mansões Águas Lindas', slug: 'mansoes-aguas-lindas', uf: 'GO', foco: 'Atendimento em Mansões Águas Lindas, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Águas Lindas' },
  { nome: 'Mansões Azaléia', slug: 'mansoes-azaleia', uf: 'GO', foco: 'Atendimento em Mansões Azaléia, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Azaléia' },
  { nome: 'Mansões Camargo', slug: 'mansoes-camargo', uf: 'GO', foco: 'Atendimento em Mansões Camargo, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Camargo' },
  { nome: 'Mansões Centro Oeste', slug: 'mansoes-centro-oeste', uf: 'GO', foco: 'Atendimento em Mansões Centro Oeste, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Centro Oeste' },
  { nome: 'Mansões Eden', slug: 'mansoes-eden', uf: 'GO', foco: 'Atendimento em Mansões Eden, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Eden' },
  { nome: 'Mansões Ilha Bela', slug: 'mansoes-ilha-bela', uf: 'GO', foco: 'Atendimento em Mansões Ilha Bela, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Ilha Bela' },
  { nome: 'Mansões Imperatriz', slug: 'mansoes-imperatriz', uf: 'GO', foco: 'Atendimento em Mansões Imperatriz, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Imperatriz' },
  { nome: 'Mansões Itamaracá', slug: 'mansoes-itamaraca', uf: 'GO', foco: 'Atendimento em Mansões Itamaracá, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Itamaracá' },
  { nome: 'Mansões Odisséia', slug: 'mansoes-odisseia', uf: 'GO', foco: 'Atendimento em Mansões Odisséia, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Odisséia' },
  { nome: 'Mansões Olinda', slug: 'mansoes-olinda', uf: 'GO', foco: 'Atendimento em Mansões Olinda, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Olinda' },
  { nome: 'Mansões Pôr do Sol', slug: 'mansoes-por-do-sol', uf: 'GO', foco: 'Atendimento em Mansões Pôr do Sol, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Pôr do Sol' },
  { nome: 'Mansões Samurai', slug: 'mansoes-samurai', uf: 'GO', foco: 'Atendimento em Mansões Samurai, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Samurai' },
  { nome: 'Mansões Savana', slug: 'mansoes-savana', uf: 'GO', foco: 'Atendimento em Mansões Savana, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Savana' },
  { nome: 'Mansões Village', slug: 'mansoes-village', uf: 'GO', foco: 'Atendimento em Mansões Village, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Mansões Village' },
  { nome: 'Park das Águas Bonitas II', slug: 'park-das-aguas-bonitas-ii', uf: 'GO', foco: 'Atendimento em Park das Águas Bonitas II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Park das Águas Bonitas II' },
  { nome: 'Parque da Barragem Setor 01', slug: 'parque-da-barragem-setor-01', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 01, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 01' },
  { nome: 'Parque da Barragem Setor 02', slug: 'parque-da-barragem-setor-02', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 02, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 02' },
  { nome: 'Parque da Barragem Setor 03', slug: 'parque-da-barragem-setor-03', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 03, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 03' },
  { nome: 'Parque da Barragem Setor 04', slug: 'parque-da-barragem-setor-04', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 04, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 04' },
  { nome: 'Parque da Barragem Setor 05', slug: 'parque-da-barragem-setor-05', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 05, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 05' },
  { nome: 'Parque da Barragem Setor 06', slug: 'parque-da-barragem-setor-06', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 06, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 06' },
  { nome: 'Parque da Barragem Setor 07', slug: 'parque-da-barragem-setor-07', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 07, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 07' },
  { nome: 'Parque da Barragem Setor 08', slug: 'parque-da-barragem-setor-08', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 08, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 08' },
  { nome: 'Parque da Barragem Setor 09', slug: 'parque-da-barragem-setor-09', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 09, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 09' },
  { nome: 'Parque da Barragem Setor 10', slug: 'parque-da-barragem-setor-10', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 10, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 10' },
  { nome: 'Parque da Barragem Setor 11', slug: 'parque-da-barragem-setor-11', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 11, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 11' },
  { nome: 'Parque da Barragem Setor 12', slug: 'parque-da-barragem-setor-12', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 12, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 12' },
  { nome: 'Parque da Barragem Setor 13', slug: 'parque-da-barragem-setor-13', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 13, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 13' },
  { nome: 'Parque da Barragem Setor 14', slug: 'parque-da-barragem-setor-14', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 14, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 14' },
  { nome: 'Parque da Barragem Setor 15', slug: 'parque-da-barragem-setor-15', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 15, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 15' },
  { nome: 'Parque da Barragem Setor 16', slug: 'parque-da-barragem-setor-16', uf: 'GO', foco: 'Atendimento em Parque da Barragem Setor 16, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque da Barragem Setor 16' },
  { nome: 'Parque das Águas Bonitas I', slug: 'parque-das-aguas-bonitas-i', uf: 'GO', foco: 'Atendimento em Parque das Águas Bonitas I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque das Águas Bonitas I' },
  { nome: 'Parque das Águas Bonitas I Etapa B', slug: 'parque-das-aguas-bonitas-i-etapa-b', uf: 'GO', foco: 'Atendimento em Parque das Águas Bonitas I Etapa B, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque das Águas Bonitas I Etapa B' },
  { nome: 'Parque do Bosque', slug: 'parque-do-bosque', uf: 'GO', foco: 'Atendimento em Parque do Bosque, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Parque do Bosque' },
  { nome: 'Recanto da Barragem', slug: 'recanto-da-barragem', uf: 'GO', foco: 'Atendimento em Recanto da Barragem, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Recanto da Barragem' },
  { nome: 'Recreio da Barragem', slug: 'recreio-da-barragem', uf: 'GO', foco: 'Atendimento em Recreio da Barragem, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Recreio da Barragem' },
  { nome: 'Recreio das Águas Lindas I', slug: 'recreio-das-aguas-lindas-i', uf: 'GO', foco: 'Atendimento em Recreio das Águas Lindas I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Recreio das Águas Lindas I' },
  { nome: 'Recreio das Águas Lindas II', slug: 'recreio-das-aguas-lindas-ii', uf: 'GO', foco: 'Atendimento em Recreio das Águas Lindas II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Recreio das Águas Lindas II' },
  { nome: 'Recreio das Águas Lindas III', slug: 'recreio-das-aguas-lindas-iii', uf: 'GO', foco: 'Atendimento em Recreio das Águas Lindas III, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Recreio das Águas Lindas III' },
  { nome: 'Residencial Jardim Paraíso', slug: 'residencial-jardim-paraiso', uf: 'GO', foco: 'Atendimento em Residencial Jardim Paraíso, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Residencial Jardim Paraíso' },
  { nome: 'Residencial Portal da Barragem', slug: 'residencial-portal-da-barragem', uf: 'GO', foco: 'Atendimento em Residencial Portal da Barragem, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Residencial Portal da Barragem' },
  { nome: 'Residencial Sol Nascente I', slug: 'residencial-sol-nascente-i', uf: 'GO', foco: 'Atendimento em Residencial Sol Nascente I, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Residencial Sol Nascente I' },
  { nome: 'Residencial Sol Nascente II', slug: 'residencial-sol-nascente-ii', uf: 'GO', foco: 'Atendimento em Residencial Sol Nascente II, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Residencial Sol Nascente II' },
  { nome: 'Royal Parque', slug: 'royal-parque', uf: 'GO', foco: 'Atendimento em Royal Parque, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Royal Parque' },
  { nome: 'Vila Esperança', slug: 'vila-esperanca', uf: 'GO', foco: 'Atendimento em Vila Esperança, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Vila Esperança' },
  { nome: 'Vivendas Paraíso', slug: 'vivendas-paraiso', uf: 'GO', foco: 'Atendimento em Vivendas Paraíso, Águas Lindas de Goiás - GO', whatsappMsg: 'Gostaria de um orçamento para Vivendas Paraíso' },
];

export const getLocalidadeBySlug = (slug: string) => {
  return localidades.find(l => slug.endsWith(l.slug));
};
