export interface Localidade {
  nome: string;
  slug: string;
  uf: 'DF' | 'GO';
  foco: string;
  whatsappMsg: string;
}

export const servicos = {
  'manutencao-eletrica': 'Manutenção Elétrica',
  'manutencao-hidraulica': 'Manutenção Hidráulica',
  'manutencao-eletronica': 'Manutenção Eletrônica'
};

export const localidades: Localidade[] = [
  { nome: 'Asa Norte', slug: 'asa-norte', uf: 'DF', foco: 'Atendimento em Asa Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Asa Norte' },
  { nome: 'Asa Sul', slug: 'asa-sul', uf: 'DF', foco: 'Atendimento em Asa Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Asa Sul' },
  { nome: 'Setor Comercial Sul', slug: 'setor-comercial-sul', uf: 'DF', foco: 'Atendimento em Setor Comercial Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Comercial Sul' },
  { nome: 'Setor Comercial Norte', slug: 'setor-comercial-norte', uf: 'DF', foco: 'Atendimento em Setor Comercial Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Comercial Norte' },
  { nome: 'Setor Bancário Sul', slug: 'setor-bancario-sul', uf: 'DF', foco: 'Atendimento em Setor Bancário Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Bancário Sul' },
  { nome: 'Setor Bancário Norte', slug: 'setor-bancario-norte', uf: 'DF', foco: 'Atendimento em Setor Bancário Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Bancário Norte' },
  { nome: 'Setor Hoteleiro Sul', slug: 'setor-hoteleiro-sul', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro Sul' },
  { nome: 'Setor Hoteleiro Norte', slug: 'setor-hoteleiro-norte', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro Norte' },
  { nome: 'Setor Hospitalar Sul', slug: 'setor-hospitalar-sul', uf: 'DF', foco: 'Atendimento em Setor Hospitalar Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hospitalar Sul' },
  { nome: 'Setor Hospitalar Norte', slug: 'setor-hospitalar-norte', uf: 'DF', foco: 'Atendimento em Setor Hospitalar Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hospitalar Norte' },
  { nome: 'Setor de Diversões Sul', slug: 'setor-de-diversoes-sul', uf: 'DF', foco: 'Atendimento em Setor de Diversões Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Diversões Sul' },
  { nome: 'Setor de Diversões Norte', slug: 'setor-de-diversoes-norte', uf: 'DF', foco: 'Atendimento em Setor de Diversões Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Diversões Norte' },
  { nome: 'Setor Militar Urbano', slug: 'setor-militar-urbano', uf: 'DF', foco: 'Atendimento em Setor Militar Urbano, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Militar Urbano' },
  { nome: 'Setor de Clubes Sul', slug: 'setor-de-clubes-sul', uf: 'DF', foco: 'Atendimento em Setor de Clubes Sul, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Clubes Sul' },
  { nome: 'Setor de Clubes Norte', slug: 'setor-de-clubes-norte', uf: 'DF', foco: 'Atendimento em Setor de Clubes Norte, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Clubes Norte' },
  { nome: 'Vila Planalto', slug: 'vila-planalto', uf: 'DF', foco: 'Atendimento em Vila Planalto, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Planalto' },
  { nome: 'Noroeste', slug: 'noroeste', uf: 'DF', foco: 'Atendimento em Noroeste, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Noroeste' },
  { nome: 'Cruzeiro Velho', slug: 'cruzeiro-velho', uf: 'DF', foco: 'Atendimento em Cruzeiro Velho, Plano Piloto - DF', whatsappMsg: 'Gostaria de um orçamento para Cruzeiro Velho' },
  { nome: 'Cruzeiro Novo', slug: 'cruzeiro-novo', uf: 'DF', foco: 'Atendimento em Cruzeiro Novo, Cruzeiro - DF', whatsappMsg: 'Gostaria de um orçamento para Cruzeiro Novo' },
  { nome: 'Sudoeste', slug: 'sudoeste', uf: 'DF', foco: 'Atendimento em Sudoeste, Sudoeste / Octogonal - DF', whatsappMsg: 'Gostaria de um orçamento para Sudoeste' },
  { nome: 'Octogonal', slug: 'octogonal', uf: 'DF', foco: 'Atendimento em Octogonal, Sudoeste / Octogonal - DF', whatsappMsg: 'Gostaria de um orçamento para Octogonal' },
  { nome: 'QI 01', slug: 'qi-01', uf: 'DF', foco: 'Atendimento em QI 01, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 01' },
  { nome: 'QI 05', slug: 'qi-05', uf: 'DF', foco: 'Atendimento em QI 05, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 05' },
  { nome: 'QI 07', slug: 'qi-07', uf: 'DF', foco: 'Atendimento em QI 07, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 07' },
  { nome: 'QI 09', slug: 'qi-09', uf: 'DF', foco: 'Atendimento em QI 09, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QI 09' },
  { nome: 'QL 02', slug: 'ql-02', uf: 'DF', foco: 'Atendimento em QL 02, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QL 02' },
  { nome: 'QL 06', slug: 'ql-06', uf: 'DF', foco: 'Atendimento em QL 06, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para QL 06' },
  { nome: 'SHIS', slug: 'shis', uf: 'DF', foco: 'Atendimento em SHIS, Lago Sul - DF', whatsappMsg: 'Gostaria de um orçamento para SHIS' },
  { nome: 'QI 03', slug: 'qi-03', uf: 'DF', foco: 'Atendimento em QI 03, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para QI 03' },
  { nome: 'Taquari', slug: 'taquari', uf: 'DF', foco: 'Atendimento em Taquari, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para Taquari' },
  { nome: 'CA', slug: 'ca', uf: 'DF', foco: 'Atendimento em CA, Lago Norte - DF', whatsappMsg: 'Gostaria de um orçamento para CA' },
  { nome: 'Taguatinga Centro', slug: 'taguatinga-centro', uf: 'DF', foco: 'Atendimento em Taguatinga Centro, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Centro' },
  { nome: 'Taguatinga Norte', slug: 'taguatinga-norte', uf: 'DF', foco: 'Atendimento em Taguatinga Norte, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Norte' },
  { nome: 'Taguatinga Sul', slug: 'taguatinga-sul', uf: 'DF', foco: 'Atendimento em Taguatinga Sul, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Taguatinga Sul' },
  { nome: 'Setor Hoteleiro', slug: 'setor-hoteleiro', uf: 'DF', foco: 'Atendimento em Setor Hoteleiro, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Hoteleiro' },
  { nome: 'Vila Dimas', slug: 'vila-dimas', uf: 'DF', foco: 'Atendimento em Vila Dimas, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Dimas' },
  { nome: 'Setor Industrial', slug: 'setor-industrial', uf: 'DF', foco: 'Atendimento em Setor Industrial, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Industrial' },
  { nome: 'QNG', slug: 'qng', uf: 'DF', foco: 'Atendimento em QNG, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNG' },
  { nome: 'QNL', slug: 'qnl', uf: 'DF', foco: 'Atendimento em QNL, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNL' },
  { nome: 'QNM', slug: 'qnm', uf: 'DF', foco: 'Atendimento em QNM, Taguatinga - DF', whatsappMsg: 'Gostaria de um orçamento para QNM' },
  { nome: 'Ceilândia Centro', slug: 'ceilandia-centro', uf: 'DF', foco: 'Atendimento em Ceilândia Centro, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Centro' },
  { nome: 'Ceilândia Norte', slug: 'ceilandia-norte', uf: 'DF', foco: 'Atendimento em Ceilândia Norte, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Norte' },
  { nome: 'Ceilândia Sul', slug: 'ceilandia-sul', uf: 'DF', foco: 'Atendimento em Ceilândia Sul, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Ceilândia Sul' },
  { nome: 'P Sul', slug: 'p-sul', uf: 'DF', foco: 'Atendimento em P Sul, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para P Sul' },
  { nome: 'P Norte', slug: 'p-norte', uf: 'DF', foco: 'Atendimento em P Norte, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para P Norte' },
  { nome: 'QNN', slug: 'qnn', uf: 'DF', foco: 'Atendimento em QNN, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para QNN' },
  { nome: 'Expansão do Setor O', slug: 'expansao-do-setor-o', uf: 'DF', foco: 'Atendimento em Expansão do Setor O, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Expansão do Setor O' },
  { nome: 'Setor O', slug: 'setor-o', uf: 'DF', foco: 'Atendimento em Setor O, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Setor O' },
  { nome: 'Sol Nascente', slug: 'sol-nascente', uf: 'DF', foco: 'Atendimento em Sol Nascente, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Sol Nascente' },
  { nome: 'Pôr do Sol', slug: 'por-do-sol', uf: 'DF', foco: 'Atendimento em Pôr do Sol, Ceilândia - DF', whatsappMsg: 'Gostaria de um orçamento para Pôr do Sol' },
  { nome: 'Samambaia Norte', slug: 'samambaia-norte', uf: 'DF', foco: 'Atendimento em Samambaia Norte, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Samambaia Norte' },
  { nome: 'Samambaia Sul', slug: 'samambaia-sul', uf: 'DF', foco: 'Atendimento em Samambaia Sul, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Samambaia Sul' },
  { nome: 'Expansão Samambaia', slug: 'expansao-samambaia', uf: 'DF', foco: 'Atendimento em Expansão Samambaia, Samambaia - DF', whatsappMsg: 'Gostaria de um orçamento para Expansão Samambaia' },
  { nome: 'Recanto das Emas Norte', slug: 'recanto-das-emas-norte', uf: 'DF', foco: 'Atendimento em Recanto das Emas Norte, Recanto das Emas - DF', whatsappMsg: 'Gostaria de um orçamento para Recanto das Emas Norte' },
  { nome: 'Recanto das Emas Sul', slug: 'recanto-das-emas-sul', uf: 'DF', foco: 'Atendimento em Recanto das Emas Sul, Recanto das Emas - DF', whatsappMsg: 'Gostaria de um orçamento para Recanto das Emas Sul' },
  { nome: 'Santa Maria Norte', slug: 'santa-maria-norte', uf: 'DF', foco: 'Atendimento em Santa Maria Norte, Santa Maria - DF', whatsappMsg: 'Gostaria de um orçamento para Santa Maria Norte' },
  { nome: 'Santa Maria Sul', slug: 'santa-maria-sul', uf: 'DF', foco: 'Atendimento em Santa Maria Sul, Santa Maria - DF', whatsappMsg: 'Gostaria de um orçamento para Santa Maria Sul' },
  { nome: 'Setor Central', slug: 'setor-central', uf: 'DF', foco: 'Atendimento em Setor Central, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Central' },
  { nome: 'Setor Oeste', slug: 'setor-oeste', uf: 'DF', foco: 'Atendimento em Setor Oeste, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Oeste' },
  { nome: 'Setor Sul', slug: 'setor-sul', uf: 'DF', foco: 'Atendimento em Setor Sul, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Sul' },
  { nome: 'Setor Norte', slug: 'setor-norte', uf: 'DF', foco: 'Atendimento em Setor Norte, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Norte' },
  { nome: 'Setor Leste', slug: 'setor-leste', uf: 'DF', foco: 'Atendimento em Setor Leste, Gama - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Leste' },
  { nome: 'Guará I', slug: 'guara-i', uf: 'DF', foco: 'Atendimento em Guará I, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para Guará I' },
  { nome: 'Guará II', slug: 'guara-ii', uf: 'DF', foco: 'Atendimento em Guará II, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para Guará II' },
  { nome: 'QE', slug: 'qe', uf: 'DF', foco: 'Atendimento em QE, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para QE' },
  { nome: 'QI', slug: 'qi', uf: 'DF', foco: 'Atendimento em QI, Guará - DF', whatsappMsg: 'Gostaria de um orçamento para QI' },
  { nome: 'Metropolitana', slug: 'metropolitana', uf: 'DF', foco: 'Atendimento em Metropolitana, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Metropolitana' },
  { nome: 'Divinéia', slug: 'divineia', uf: 'DF', foco: 'Atendimento em Divinéia, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Divinéia' },
  { nome: 'Candangolândia', slug: 'candangolandia', uf: 'DF', foco: 'Atendimento em Candangolândia, Núcleo Bandeirante - DF', whatsappMsg: 'Gostaria de um orçamento para Candangolândia' },
  { nome: 'Águas Claras Sul', slug: 'aguas-claras-sul', uf: 'DF', foco: 'Atendimento em Águas Claras Sul, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Águas Claras Sul' },
  { nome: 'Águas Claras Norte', slug: 'aguas-claras-norte', uf: 'DF', foco: 'Atendimento em Águas Claras Norte, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Águas Claras Norte' },
  { nome: 'Arniqueiras', slug: 'arniqueiras', uf: 'DF', foco: 'Atendimento em Arniqueiras, Águas Claras - DF', whatsappMsg: 'Gostaria de um orçamento para Arniqueiras' },
  { nome: 'Colônia Agrícola Samambaia', slug: 'colonia-agricola-samambaia', uf: 'DF', foco: 'Atendimento em Colônia Agrícola Samambaia, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Colônia Agrícola Samambaia' },
  { nome: 'Rua 03', slug: 'rua-03', uf: 'DF', foco: 'Atendimento em Rua 03, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 03' },
  { nome: 'Rua 08', slug: 'rua-08', uf: 'DF', foco: 'Atendimento em Rua 08, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 08' },
  { nome: 'Rua 12', slug: 'rua-12', uf: 'DF', foco: 'Atendimento em Rua 12, Vicente Pires - DF', whatsappMsg: 'Gostaria de um orçamento para Rua 12' },
  { nome: 'Riacho Fundo I', slug: 'riacho-fundo-i', uf: 'DF', foco: 'Atendimento em Riacho Fundo I, Riacho Fundo - DF', whatsappMsg: 'Gostaria de um orçamento para Riacho Fundo I' },
  { nome: 'Riacho Fundo II', slug: 'riacho-fundo-ii', uf: 'DF', foco: 'Atendimento em Riacho Fundo II, Riacho Fundo - DF', whatsappMsg: 'Gostaria de um orçamento para Riacho Fundo II' },
  { nome: 'Paranoá Centro', slug: 'paranoa-centro', uf: 'DF', foco: 'Atendimento em Paranoá Centro, Paranoá - DF', whatsappMsg: 'Gostaria de um orçamento para Paranoá Centro' },
  { nome: 'Itapoã', slug: 'itapoa', uf: 'DF', foco: 'Atendimento em Itapoã, Paranoá - DF', whatsappMsg: 'Gostaria de um orçamento para Itapoã' },
  { nome: 'Sobradinho I', slug: 'sobradinho-i', uf: 'DF', foco: 'Atendimento em Sobradinho I, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Sobradinho I' },
  { nome: 'Sobradinho II', slug: 'sobradinho-ii', uf: 'DF', foco: 'Atendimento em Sobradinho II, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Sobradinho II' },
  { nome: 'Nova Colina', slug: 'nova-colina', uf: 'DF', foco: 'Atendimento em Nova Colina, Sobradinho - DF', whatsappMsg: 'Gostaria de um orçamento para Nova Colina' },
  { nome: 'Setor Tradicional', slug: 'setor-tradicional', uf: 'DF', foco: 'Atendimento em Setor Tradicional, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Setor Tradicional' },
  { nome: 'Arapoanga', slug: 'arapoanga', uf: 'DF', foco: 'Atendimento em Arapoanga, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Arapoanga' },
  { nome: 'Vale do Amanhecer', slug: 'vale-do-amanhecer', uf: 'DF', foco: 'Atendimento em Vale do Amanhecer, Planaltina - DF', whatsappMsg: 'Gostaria de um orçamento para Vale do Amanhecer' },
  { nome: 'Jardim Botânico', slug: 'jardim-botanico', uf: 'DF', foco: 'Atendimento em Jardim Botânico, Jardim Botânico - DF', whatsappMsg: 'Gostaria de um orçamento para Jardim Botânico' },
  { nome: 'São Sebastião', slug: 'sao-sebastiao', uf: 'DF', foco: 'Atendimento em São Sebastião, Jardim Botânico - DF', whatsappMsg: 'Gostaria de um orçamento para São Sebastião' },
  { nome: 'Vila Nova', slug: 'vila-nova', uf: 'DF', foco: 'Atendimento em Vila Nova, São Sebastião - DF', whatsappMsg: 'Gostaria de um orçamento para Vila Nova' },
  { nome: 'Morro Azul', slug: 'morro-azul', uf: 'DF', foco: 'Atendimento em Morro Azul, São Sebastião - DF', whatsappMsg: 'Gostaria de um orçamento para Morro Azul' },
  { nome: 'SMPW', slug: 'smpw', uf: 'DF', foco: 'Atendimento em SMPW, Park Way - DF', whatsappMsg: 'Gostaria de um orçamento para SMPW' },
  { nome: 'Quadras Park Way', slug: 'quadras-park-way', uf: 'DF', foco: 'Atendimento em Quadras Park Way, Park Way - DF', whatsappMsg: 'Gostaria de um orçamento para Quadras Park Way' },
  { nome: 'Setor de Indústria e Abastecimento', slug: 'setor-de-industria-e-abastecimento', uf: 'DF', foco: 'Atendimento em Setor de Indústria e Abastecimento, SIA - DF', whatsappMsg: 'Gostaria de um orçamento para Setor de Indústria e Abastecimento' },
  { nome: 'Cidade Estrutural', slug: 'cidade-estrutural', uf: 'DF', foco: 'Atendimento em Cidade Estrutural, Estrutural - DF', whatsappMsg: 'Gostaria de um orçamento para Cidade Estrutural' },
];

export const getLocalidadeBySlug = (slug: string) => {
  return localidades.find(l => slug.endsWith(l.slug));
};
